#! /bin/bash
#			Made by Cyberw1nd at GPL.

#			fuckin thumbnail files escaped by directory_killer
rm --verbose /home/thorsten/Bilder/*0a*
rm --verbose /home/thorsten/Bilder/*1a*
rm --verbose /home/thorsten/Bilder/*2a*
rm --verbose /home/thorsten/Bilder/*3a*
rm --verbose /home/thorsten/Bilder/*4a*
rm --verbose /home/thorsten/Bilder/*5a*
rm --verbose /home/thorsten/Bilder/*6a*
rm --verbose /home/thorsten/Bilder/*7a*
rm --verbose /home/thorsten/Bilder/*8a*
rm --verbose /home/thorsten/Bilder/*9a*
rm --verbose /home/thorsten/Bilder/*0b*
rm --verbose /home/thorsten/Bilder/*1b*
rm --verbose /home/thorsten/Bilder/*2b*
rm --verbose /home/thorsten/Bilder/*3b*
rm --verbose /home/thorsten/Bilder/*4b*
rm --verbose /home/thorsten/Bilder/*5b*
rm --verbose /home/thorsten/Bilder/*6b*
rm --verbose /home/thorsten/Bilder/*7b*
rm --verbose /home/thorsten/Bilder/*8b*
rm --verbose /home/thorsten/Bilder/*9b*
rm --verbose /home/thorsten/Bilder/*0c*
rm --verbose /home/thorsten/Bilder/*1c*
rm --verbose /home/thorsten/Bilder/*2c*
rm --verbose /home/thorsten/Bilder/*3c*
rm --verbose /home/thorsten/Bilder/*4c*
rm --verbose /home/thorsten/Bilder/*5c*
rm --verbose /home/thorsten/Bilder/*6c*
rm --verbose /home/thorsten/Bilder/*7c*
rm --verbose /home/thorsten/Bilder/*8c*
rm --verbose /home/thorsten/Bilder/*9c*
rm --verbose /home/thorsten/Bilder/*0d*
rm --verbose /home/thorsten/Bilder/*1d*
rm --verbose /home/thorsten/Bilder/*2d*
rm --verbose /home/thorsten/Bilder/*3d*
rm --verbose /home/thorsten/Bilder/*4d*
rm --verbose /home/thorsten/Bilder/*5d*
rm --verbose /home/thorsten/Bilder/*6d*
rm --verbose /home/thorsten/Bilder/*7d*
rm --verbose /home/thorsten/Bilder/*8d*
rm --verbose /home/thorsten/Bilder/*9d*
rm --verbose /home/thorsten/Bilder/*0e*
rm --verbose /home/thorsten/Bilder/*1e*
rm --verbose /home/thorsten/Bilder/*2e*
rm --verbose /home/thorsten/Bilder/*3e*
rm --verbose /home/thorsten/Bilder/*4e*
rm --verbose /home/thorsten/Bilder/*5e*
rm --verbose /home/thorsten/Bilder/*6e*
rm --verbose /home/thorsten/Bilder/*7e*
rm --verbose /home/thorsten/Bilder/*8e*
rm --verbose /home/thorsten/Bilder/*9e*
rm --verbose /home/thorsten/Bilder/*0f*
rm --verbose /home/thorsten/Bilder/*1f*
rm --verbose /home/thorsten/Bilder/*2f*
rm --verbose /home/thorsten/Bilder/*3f*
rm --verbose /home/thorsten/Bilder/*4f*
rm --verbose /home/thorsten/Bilder/*5f*
rm --verbose /home/thorsten/Bilder/*6f*
rm --verbose /home/thorsten/Bilder/*7f*
rm --verbose /home/thorsten/Bilder/*8f*
rm --verbose /home/thorsten/Bilder/*9f*
