#!/bin/bash
rm found.txt

source_dir="$1";
root_target="$2";
echo "generating filePathList of directory '$source_dir'"
find $source_dir > source_paths.txt
echo "generating filePathList of directory '$root_target'"
find $root_target > target_paths.txt
source_lengh=$(cat source_paths.txt | wc -l)
for iSource in $(seq 1 1 $source_lengh)
do
	filename=$(cat source_paths.txt | awk NR==$iSource | rev | cut -d '/' -f 1 | rev | sort)
	echo "$filename" >> source_names.txt
	if grep -q "$filename" target_paths.txt 
	then
		path=$(grep "$filename" target_paths.txt)
		echo "$path" >> found.txt
		isFound=$path
	else
		path=$(grep "$filename" source_paths.txt)
		echo "$path" >> missing.txt
		isFound=$path
	fi
	if [ $(expr $iSource % 64) == 0 ] #useroutput
	then
		clear;
		echo "generating filelist of directory '$source_dir' ...done"
		echo "generating filelist of directory '$root_target' ...done"
		echo "converting filelist of directory '$source_dir':--->"
		echo "    task: extract filename from fullpath: "
		echo "    grepping for filename $iSource/$source_lengh == $filename"
		echo "    in the filePathList of directory $root_target == $isFound"
		echo "lists are stored in the files 'found.txt' and 'missing.txt'"

	fi
done




#target_lengh=$(cat target.txt | wc -l)
#for iTarget in $(seq 1 1 $target_lengh)
#do
#	filename=$(cat target.txt | awk NR==$iTarget |  rev | cut -d '/' -f 1 | rev | sort)
#	echo "$filename" >> target.txt
#	if [ $(expr $iTarget % 64) == 0 ]
#	then
#		clear;
#		echo "generating filelist of directory '$source_dir' ...done"
#		echo "generating filelist of directory '$root_target' ...done"
#		echo "converting filelist of directory '$source_dir' ...done"
#		echo "grepping for filenames of the files onder the root '$source_dir' ...done"
#		echo "in the list of the filepaths onder the root '$root_target' ...done"
#		echo "converting filelist of directory '$root_target':--->"
#		printf "task: extract filename from fullpath: "
#		printf "$iTarget/$target_lengh"
#	fi
#done
#echo " ...done"

