#!/bin/bash
rm found.txt 
rm missing.txt 
rm source_names.txt 
rm source_paths.txt 
rm target_paths.txt 
rm -r missing_files/
iFound=0
iMissing=0
source_dir="$1";
root_target="$2";
echo "generating filePathList of directory '$source_dir'"
find $source_dir > source_paths.txt
echo "generating filePathList of directory '$root_target'"
find $root_target > target_paths.txt
source_lengh=$(cat source_paths.txt | wc -l)
for iSource in $(seq 1 1 $source_lengh)
do
	filename=$(cat source_paths.txt | awk NR==$iSource | rev | cut -d '/' -f 1 | rev | sort)
	echo "$filename" >> source_names.txt
	if grep -q "$filename" target_paths.txt 
	then
		path="$(grep "$filename" target_paths.txt)"
		echo "$path" >> found.txt
		isFound="found"
		let iFound++
	else
		path=$(grep "$filename" source_paths.txt)
		echo "$path" >> missing.txt
		isFound="missing"
		let iMissing++
	fi

	if [ $(expr $iSource % 64) == 0 ] #useroutput
	then
		clear;
		echo "generating filelist of directory '$source_dir' ...done"
		echo "generating filelist of directory '$root_target' ...done"
		echo "converting filelist of directory '$source_dir':--->"
		echo "    task: extract filename from fullpath: "
		echo "    grepping for filename $iSource/$source_lengh == $filename"
		echo "    in the filePathList of directory $root_target == $isFound"
		echo "lists are stored in the files 'found.txt' and 'missing.txt'"
		echo "found/missing: $(cat found.txt | wc -l)/$(cat missing.txt | wc -l ) "
	fi
done

read -p "link all missing files to the folder 'missing_files'? [y/n]" answer
if [ "y" == $answer ]
then
	mkdir missing_files
	for i in $(seq 1 1 $(cat missing.txt | wc -l))
	do
		ln -s "$(cat missing.txt | awk NR==$i)" missing_files/
		lines=$( cat missing.txt | wc -l)
		
		if [ $(expr $i % 64) == 0 ] #useroutput
		then
			clear;
			echo "generating filelist of directory '$source_dir' ...done"
			echo "generating filelist of directory '$root_target' ...done"
			echo "converting filelist of directory '$source_dir':--->"
			echo "    task: extract filename from fullpath: "
			echo "    grepping for filename $iSource/$source_lengh == $filename"
			echo "    in the filePathList of directory $root_target == $isFound"
			echo "lists are stored in the files 'found.txt' and 'missing.txt'"
			echo "found/missing: $iFound/$iMissing "
			echo "creating link $i/$lines"
		fi
	done
fi
